### ISSUE TITLE
Screenshot problem with Mario & Luigi:Paper Jam Bros.

### ISSUE THREAD

**Issue by Shadow322** [44670/BootNTR#23]
@44670 when taking screen shots it cuts off a section of the top screen making that area black then takes a section to the left of that black area and pastes it to the bottom screen shot this all happen on the right side of the screen.

**Comment by spacemul** [comment]
I don't know if anyone can modified, but same problem with screenshots function in game like Luigi's Mansion 2, all Nintendogs games, Ace Combat

I make screenshots for all 3DS games for my website, exemple of screnshots 

![41190](https://cloud.githubusercontent.com/assets/7451522/13187415/2330fff2-d74b-11e5-9889-f56540a50b27.png)
![40932](https://cloud.githubusercontent.com/assets/7451522/13187421/2e695a72-d74b-11e5-84e2-519b8f09e3d6.png)

**Comment by 44670** [comment]
I think it may have fixed now.

**Comment by Shadow322** [comment]
So fixed in next release?

**Comment by 44670** [comment]
oh, I was wrong. The problem still exists and current it could be solved by setting hot-keys.

**Comment by Shadow322** [comment]
Nope setting hot keys does not solve it as it's still happening
